services:
    # BACKEND
    backend:
      container_name: "cv-query-assistant-backend"
      build:
        context: .
        dockerfile: Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/app
      env_file:
        - .env
      ports:
        - "8000:8000"
      depends_on:
        - postgres
        - mongo
      networks:
        - curriculum-vitae-query-assistant-network

    # POSTGRESQL
    postgres:
      image: "postgres:17.4-bullseye"
      container_name: "cv-query-assistant-postgres"
      environment:
        - "POSTGRES_DB=${POSTGRESQL_DATABASE_NAME}"
        - "POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}"
        - "POSTGRES_USER=${POSTGRESQL_USERNAME}"
      ports:
        - "${POSTGRESQL_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - curriculum-vitae-query-assistant-network

    # PGADMIN
    pgadmin:
      image: "dpage/pgadmin4:9.2"
      container_name: "cv-query-assistant-pgadmin"
      environment:
        - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_USERNAME}"
        - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}"
      ports:
        - "${PGADMIN_PORT}:80"
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - curriculum-vitae-query-assistant-network

    # MONGODB
    mongo:
      image: "mongo:8.0.8"
      container_name: "cv-query-assistant-mongo"
      environment:
        - "MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}"
        - "MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}"
      ports:
        - "${MONGODB_PORT}:27017"
      volumes:
        - mongodb_data:/data/db
      networks:
        - curriculum-vitae-query-assistant-network

    # MONGO-EXPRESS
    mongo-express:
      image: "mongo-express"
      container_name: "cv-query-assistant-mongo-express"
      environment:
        - "ME_CONFIG_MONGODB_SERVER=mongo"
        - "ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}"
        - "ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}"
        - "ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}"
        - "ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}"
        - "ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}"
      ports:
        - "${MONGO_EXPRESS_PORT}:8081"
      depends_on:
        - mongo
      networks:
        - curriculum-vitae-query-assistant-network

networks:
  curriculum-vitae-query-assistant-network:
    name: curriculum-vitae-query-assistant-network
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  mongodb_data: