services:
    # BACKEND
    backend:
      container_name: "cv-query-assistant-backend"
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/curriculum-vitae-query-assistant
      env_file:
        - .env
      ports:
        - "8000:8000"
      depends_on:
        - mongo
      networks:
        - curriculum-vitae-query-assistant-network

    # MONGODB
    mongo:
      hostname: ${MONGODB_HOST}
      image: "mongo:8.0.8"
      container_name: "cv-query-assistant-mongo"
      environment:
        - "MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}"
        - "MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}"
      ports:
        - "${MONGODB_PORT}:27017"
      volumes:
        - mongodb_data:/data/db
      networks:
        - curriculum-vitae-query-assistant-network

    # MONGO-EXPRESS
    mongo-express:
      image: "mongo-express"
      container_name: "cv-query-assistant-mongo-express"
      environment:
        - "ME_CONFIG_MONGODB_SERVER=mongo"
        - "ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}"
        - "ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}"
        - "ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}"
        - "ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}"
        - "ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}"
      ports:
        - "${MONGO_EXPRESS_PORT}:8081"
      depends_on:
        - mongo
      networks:
        - curriculum-vitae-query-assistant-network

networks:
  curriculum-vitae-query-assistant-network:
    name: curriculum-vitae-query-assistant-network
    driver: bridge

volumes:
  mongodb_data: